### ISSUE TITLE
Units in frequency spectrum plot

### ISSUE THREAD

**Issue by moorepants** [csu-hmc/perturbed-data-paper#117]
v^2/Hz should be m^2s^-2/Hz. I don't think v (as units) is defined anywhere.

**Comment by moorepants** [comment]
Ah, this is still odd.

It should be:
```tex
m^2 s^{-2} Hz^{-1}
```
or
```tex
\frac{m^2}{s^2 Hz}
```
or a one line with `\`.

**Comment by tvdbogert** [comment]
It was correct but just looked odd with the mix of exponent and slash notation.

I think I would prefer the notation m^2 s^{-2} Hz^{-1}

Which is technically the same as m^2 s^{-1} but that would make it more confusing.

The results are a power spectral density, produced with Matlab's "spectrogram" function
Power is the square of the velocity signal, so m^2/s^2. Then density makes this power per Hz, i.e. m^2/s^2/Hz
