### ISSUE TITLE
ValueError: too many values to unpack

### ISSUE THREAD

**Issue by nag92** [csu-hmc/perturbed-data-paper#177]
When running `python src/unperturbed_perturbed_comparison.py`
The terminal just sits there and I have to kill it. When I do I get the following error.

`Traceback (most recent call last):
  File "src/unperturbed_perturbed_comparison.py", line 43, in <module>
    unperturbed_gait_data_1 = load_data('First Normal Walking', paths, tmp)
  File "/home/nathaniel/perturbed-data-paper/src/utils.py", line 116, in load_data
    gait_data.inverse_dynamics_2d(*args)
  File "/home/nathaniel/anaconda2/envs/gait/lib/python2.7/site-packages/gaitanalysis/gait.py", line 213, in inverse_dynamics_2d
    octave.addpath(m_file_directory)
  File "/home/nathaniel/anaconda2/envs/gait/lib/python2.7/site-packages/oct2py/core.py", line 539, in __getattr__
    doc = self._get_doc(name)
  File "/home/nathaniel/anaconda2/envs/gait/lib/python2.7/site-packages/oct2py/core.py", line 508, in _get_doc
    verbose=False, return_both=True)
ValueError: too many values to unpack`

**Comment by moorepants** [comment]
I recommend using the exact software versions specified in the README. We have not maintained this software since publishing this paper, so any new software you use may have different results. Please list the versions of all the dependencies you are using.

**Comment by nag92** [comment]
I remade the conda workspace with the following depenance
I am on a 16.04 machine. 

`# packages in environment at /home/nathaniel/anaconda/envs/gait:
#
actionlib                 1.11.9                    <pip>
anaconda-client           1.6.3                    py27_0  
angles                    1.9.11                    <pip>
base-local-planner        1.14.2                    <pip>
binstar                   0.12                          2  
bondpy                    1.7.19                    <pip>
cairo                     1.12.18                       0  
camera-calibration        1.12.20                   <pip>
camera-calibration-parsers 1.11.12                   <pip>
capabilities              0.2.0                     <pip>
catkin                    0.7.6                     <pip>
certifi                   2016.2.28                py27_0  
clyent                    1.2.2                    py27_0  
create-driver             2.3.1                     <pip>
create-node               2.3.1                     <pip>
cv-bridge                 1.12.4                    <pip>
dateutil                  2.4.1                    py27_0  
diagnostic-analysis       1.9.2                     <pip>
diagnostic-common-diagnostics 1.9.2                     <pip>
diagnostic-updater        1.9.2                     <pip>
dynamic-reconfigure       1.5.48                    <pip>
dynamicisttoolkit         0.3.5                     <pip>
expat                     2.1.0                         0  
freetype                  2.4.10                        0  
gaitanalysistoolkit       0.1.2                     <pip>
gazebo-plugins            2.5.13                    <pip>
gazebo-ros                2.5.13                    <pip>
gencpp                    0.5.5                     <pip>
geneus                    2.2.6                     <pip>
genlisp                   0.4.16                    <pip>
genmsg                    0.5.8                     <pip>
gennodejs                 2.0.1                     <pip>
genpy                     0.6.5                     <pip>
hdf5                      1.8.14                        0  
icu                       54.1                          0  
image-geometry            1.12.4                    <pip>
interactive-markers       1.11.3                    <pip>
laser-geometry            1.6.4                     <pip>
libgcc                    5.2.0                         0  
libgfortran               3.0.0                         1  
libiconv                  1.14                          0  
libpng                    1.5.13                        1  
matplotlib                1.4.2                np19py27_0  
message-filters           1.12.7                    <pip>
numexpr                   2.3.1                np19py27_0  
numpy                     1.9.1                    py27_0  
oct2py                    2.4.2                     <pip>
openssl                   1.0.2l                        0  
pandas                    0.15.1               np19py27_0  
pip                       9.0.1                    py27_1  
pixman                    0.26.2                        0  
pluginlib                 1.10.5                    <pip>
py2cairo                  1.10.0                   py27_2  
pygments                  2.0.1                    py27_0  
pyparsing                 2.0.1                    py27_0  
pyqt                      4.10.4                   py27_0  
pytables                  3.1.1                np19py27_2  
python                    2.7.13                        0  
python-dateutil           2.6.1                    py27_0  
python-qt-binding         0.3.2                     <pip>
pytz                      2017.2                   py27_0  
pyyaml                    3.12                     py27_0  
qt                        4.8.5                         0  
qt-dotgraph               0.3.4                     <pip>
qt-gui                    0.3.4                     <pip>
qt-gui-cpp                0.3.4                     <pip>
qt-gui-py-common          0.3.4                     <pip>
readline                  6.2                           2  
requests                  2.14.2                   py27_0  
resource-retriever        1.12.3                    <pip>
rocon-app-manager         0.9.1                     <pip>
rocon-app-utilities       0.9.1                     <pip>
rocon-apps                0.9.1                     <pip>
rocon-console             0.3.2                     <pip>
rocon-ebnf                0.3.2                     <pip>
rocon-gateway             0.8.1                     <pip>
rocon-gateway-utils       0.8.1                     <pip>
rocon-hub                 0.8.1                     <pip>
rocon-hub-client          0.8.1                     <pip>
rocon-interactions        0.3.2                     <pip>
rocon-master-info         0.3.2                     <pip>
rocon-python-comms        0.3.2                     <pip>
rocon-python-redis        0.3.2                     <pip>
rocon-python-utils        0.3.2                     <pip>
rocon-python-wifi         0.3.2                     <pip>
rocon-semantic-version    0.3.2                     <pip>
rocon-uri                 0.3.2                     <pip>
rosbag                    1.12.7                    <pip>
rosboost-cfg              1.13.5                    <pip>
rosclean                  1.13.5                    <pip>
roscreate                 1.13.5                    <pip>
rosgraph                  1.12.7                    <pip>
roslaunch                 1.12.7                    <pip>
roslib                    1.13.5                    <pip>
roslint                   0.11.0                    <pip>
roslz4                    1.12.7                    <pip>
rosmake                   1.13.5                    <pip>
rosmaster                 1.12.7                    <pip>
rosmsg                    1.12.7                    <pip>
rosnode                   1.12.7                    <pip>
rosparam                  1.12.7                    <pip>
rospy                     1.12.7                    <pip>
rospy-message-converter   0.4.0                     <pip>
rosservice                1.12.7                    <pip>
rostest                   1.12.7                    <pip>
rostopic                  1.12.7                    <pip>
rosunit                   1.13.5                    <pip>
roswtf                    1.12.7                    <pip>
rqt-action                0.4.9                     <pip>
rqt-bag                   0.4.8                     <pip>
rqt-bag-plugins           0.4.8                     <pip>
rqt-console               0.4.8                     <pip>
rqt-dep                   0.4.8                     <pip>
rqt-graph                 0.4.8                     <pip>
rqt-gui                   0.5.0                     <pip>
rqt-gui-py                0.5.0                     <pip>
rqt-image-view            0.4.9                     <pip>
rqt-launch                0.4.8                     <pip>
rqt-logger-level          0.4.8                     <pip>
rqt-moveit                0.5.7                     <pip>
rqt-msg                   0.4.8                     <pip>
rqt-nav-view              0.5.7                     <pip>
rqt-plot                  0.4.8                     <pip>
rqt-pose-view             0.5.7                     <pip>
rqt-publisher             0.4.8                     <pip>
rqt-py-common             0.5.0                     <pip>
rqt-py-console            0.4.8                     <pip>
rqt-reconfigure           0.4.8                     <pip>
rqt-robot-dashboard       0.5.7                     <pip>
rqt-robot-monitor         0.5.7                     <pip>
rqt-robot-steering        0.5.7                     <pip>
rqt-runtime-monitor       0.5.7                     <pip>
rqt-rviz                  0.5.7                     <pip>
rqt-service-caller        0.4.8                     <pip>
rqt-shell                 0.4.9                     <pip>
rqt-srv                   0.4.8                     <pip>
rqt-tf-tree               0.5.8                     <pip>
rqt-top                   0.4.8                     <pip>
rqt-topic                 0.4.8                     <pip>
rqt-web                   0.4.8                     <pip>
rviz                      1.12.13                   <pip>
scipy                     0.14.0               np19py27_0  
seaborn                   0.5.0                np19py27_0  
sensor-msgs               1.12.5                    <pip>
setuptools                36.4.0                   py27_1  
sip                       4.15.5                   py27_0  
six                       1.10.0                   py27_0  
smach                     2.0.1                     <pip>
smach-ros                 2.0.1                     <pip>
smclib                    1.7.19                    <pip>
sqlite                    3.13.0                        0  
tables                    3.1.1                     <pip>
tf                        1.11.9                    <pip>
tf-conversions            1.11.9                    <pip>
tf2-geometry-msgs         0.5.16                    <pip>
tf2-kdl                   0.5.16                    <pip>
tf2-py                    0.5.16                    <pip>
tf2-ros                   0.5.16                    <pip>
tk                        8.5.18                        0  
topic-tools               1.12.7                    <pip>
unique-id                 1.0.5                     <pip>
wheel                     0.29.0                   py27_0  
xacro                     1.11.2                    <pip>
yaml                      0.1.6                         0  
zlib                      1.2.11                        0  `

**Comment by nag92** [comment]
I also know get an error
`ImportError: libgfortran.so.1: cannot open shared object file: No such file or directory`

**Comment by moorepants** [comment]
Here is a note about the error: https://github.com/ContinuumIO/anaconda-issues/issues/445

**Comment by nag92** [comment]
I solved that error but I am still getting `ValueError: too many values to unpack
` error

**Comment by moorepants** [comment]
Instead of listing every single package you have installed in conda, it would be helpful if you listed only the packages that are listed in the README.

**Comment by nag92** [comment]
I think that is has to do with Oct2py. That seems to be what is throwing the error



`
numpy                     1.9.1,
oct2py                    2.4.2, 
pandas                    0.15.1,
pytables                  3.1.1,  
python                    2.7.13,     
pyyaml                    3.11,                   
scipy                     0.14.0 , 
seaborn                   0.5.0,  
libgfortran               1.0,  
dynamicisttoolkit         0.3.5,
gaitanalysistoolkit       0.1.2,
matplotlib                1.4.2,  
pygments                  2.0.1
 `

**Comment by nag92** [comment]
It was a problem with Octave, I was using 4.x, I uninstalled it and installed 3.8.2 and it work.

**Comment by moorepants** [comment]
Good, glad you found the error. I think that GaitAnalysisToolkit needs to be updated to work with current dependency versions.

**Comment by moorepants** [comment]
FYI, GaitAnalysisToolKit has been updated to work with recent dependency versions.
