### ISSUE TITLE
Reference to figure 2 and 3 in the beginning of the paragraph

### ISSUE THREAD

**Issue by adkoele** [csu-hmc/perturbed-data-paper#92]

**Comment by moorepants** [comment]
@adkoele Do you remember what this means? I forget what you wanted us to change. Was it just that you thought the sentences should lead with "Figure X shows..."?

**Comment by adkoele** [comment]
Yes, we decided that it was best if the section starts with Figure X, since
when I read it, I completely missed the reference

2015-01-13 14:34 GMT-05:00 Jason K. Moore <notifications@github.com>:

**Comment by moorepants** [comment]
Do you mean the section, the paragraph, or the sentence?

**Comment by adkoele** [comment]
The beginning of the paragraph I think (I'm not sure what the difference is
between paragraph and section..).

2015-01-13 18:43 GMT-05:00 Jason K. Moore <notifications@github.com>:

**Comment by moorepants** [comment]
Ok, thanks. Section has a specific definition in LaTeX. In this case, this section is "Perturbation Signals" (and more precisely it is a sub-section). I'll rework the sentence.

**Comment by adkoele** [comment]
I see, thanks for explaining.. It's the paragraph

2015-01-13 18:54 GMT-05:00 Jason K. Moore <notifications@github.com>:
